2020-10-18 13:22:47,373     CRITICAL     server_log_config.py     Критическая ошибка
2020-10-18 13:22:47,375     ERROR        server_log_config.py     Ошибка
2020-10-18 13:22:47,376     DEBUG        server_log_config.py     Отладочная информация
2020-10-18 13:22:47,376     INFO         server_log_config.py     Информационное сообщение
2020-10-18 13:23:22,856     CRITICAL     server_log_config.py     Критическая ошибка
2020-10-18 13:23:22,856     ERROR        server_log_config.py     Ошибка
2020-10-18 13:23:22,856     DEBUG        server_log_config.py     Отладочная информация
2020-10-18 13:23:22,856     INFO         server_log_config.py     Информационное сообщение
2020-10-18 13:23:27,431     CRITICAL     server_log_config.py     Критическая ошибка
2020-10-18 13:23:27,431     ERROR        server_log_config.py     Ошибка
2020-10-18 13:23:27,431     DEBUG        server_log_config.py     Отладочная информация
2020-10-18 13:23:27,431     INFO         server_log_config.py     Информационное сообщение
2020-10-18 13:23:44,062     CRITICAL     server_log_config.py     Критическая ошибка
2020-10-18 13:23:44,062     ERROR        server_log_config.py     Ошибка
2020-10-18 13:23:44,062     DEBUG        server_log_config.py     Отладочная информация
2020-10-18 13:23:44,063     INFO         server_log_config.py     Информационное сообщение
2020-10-18 14:28:25,129     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 14:28:35,250     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 52743)
2020-10-18 14:28:35,251     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603020515.250023, 'user': {'account_name': 'Guest'}}
2020-10-18 14:28:35,251     DEBUG        server.py                Разбор сообщения от клиента : {'action': 'presence', 'time': 1603020515.250023, 'user': {'account_name': 'Guest'}}
2020-10-18 14:28:35,251     INFO         server.py                Cформирован ответ клиенту {'response': 200}
2020-10-18 14:28:35,252     DEBUG        server.py                Соединение с клиентом ('127.0.0.1', 52743) закрывается.
2020-10-18 14:36:05,776     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 14:36:52,623     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 53173)
2020-10-18 14:36:52,623     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603021012.6236832, 'user': {'account_name': 'Guest'}}
2020-10-18 14:36:52,624     DEBUG        server.py                Разбор сообщения от клиента : {'action': 'presence', 'time': 1603021012.6236832, 'user': {'account_name': 'Guest'}}
2020-10-18 14:36:52,624     INFO         server.py                Cформирован ответ клиенту {'response': 200}
2020-10-18 14:36:52,624     DEBUG        server.py                Соединение с клиентом ('127.0.0.1', 53173) закрывается.
2020-10-18 15:07:35,133     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 53479)
2020-10-18 15:07:35,133     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603022855.1333091, 'user': {'account_name': 'Guest'}}
2020-10-18 15:07:35,134     ERROR        server.py                От клиента ('127.0.0.1', 53479) приняты некорректные данные. Соединение закрывается.
2020-10-18 15:07:35,282     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 53480)
2020-10-18 15:07:35,282     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603022855.2829394, 'user': {'account_name': 'Guest'}}
2020-10-18 15:07:35,283     ERROR        server.py                От клиента ('127.0.0.1', 53480) приняты некорректные данные. Соединение закрывается.
2020-10-18 15:07:35,286     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 53481)
2020-10-18 15:07:35,287     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603022855.286935, 'user': {'account_name': 'Guest'}}
2020-10-18 15:07:35,287     ERROR        server.py                От клиента ('127.0.0.1', 53481) приняты некорректные данные. Соединение закрывается.
2020-10-18 15:07:35,300     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:07:35,301     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 53482)
2020-10-18 15:07:35,302     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603022855.3019218, 'user': {'account_name': 'Guest'}}
2020-10-18 15:07:35,302     ERROR        server.py                От клиента ('127.0.0.1', 53482) приняты некорректные данные. Соединение закрывается.
2020-10-18 15:07:35,373     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 53483)
2020-10-18 15:07:35,373     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603022855.3738542, 'user': {'account_name': 'Guest'}}
2020-10-18 15:07:35,374     ERROR        server.py                От клиента ('127.0.0.1', 53483) приняты некорректные данные. Соединение закрывается.
2020-10-18 15:07:52,769     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:09:31,414     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:12:55,432     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:16:09,219     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:16:20,274     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 54283)
2020-10-18 15:16:20,275     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603023380.2741718, 'user': {'account_name': 'Guest'}}
2020-10-18 15:16:20,275     ERROR        server.py                От клиента ('127.0.0.1', 54283) приняты некорректные данные. Соединение закрывается.
2020-10-18 15:24:11,672     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:24:17,963     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 54511)
2020-10-18 15:24:17,964     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603023857.9635131, 'user': {'account_name': 'Guest'}}
2020-10-18 15:24:17,964     DEBUG        server.py                Разбор сообщения от клиента : {'action': 'presence', 'time': 1603023857.9635131, 'user': {'account_name': 'Guest'}}
2020-10-18 15:24:17,964     INFO         server.py                Cформирован ответ клиенту {'response': 200}
2020-10-18 15:24:17,965     DEBUG        server.py                Соединение с клиентом ('127.0.0.1', 54511) закрывается.
2020-10-18 15:26:08,332     CRITICAL     server_log_config.py     Критическая ошибка
2020-10-18 15:26:08,332     ERROR        server_log_config.py     Ошибка
2020-10-18 15:26:08,332     DEBUG        server_log_config.py     Отладочная информация
2020-10-18 15:26:08,333     INFO         server_log_config.py     Информационное сообщение
2020-10-18 15:26:19,872     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:26:22,712     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 54590)
2020-10-18 15:26:22,713     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603023982.71377, 'user': {'account_name': 'Guest'}}
2020-10-18 15:26:22,714     DEBUG        server.py                Разбор сообщения от клиента : {'action': 'presence', 'time': 1603023982.71377, 'user': {'account_name': 'Guest'}}
2020-10-18 15:26:22,714     INFO         server.py                Cформирован ответ клиенту {'response': 200}
2020-10-18 15:26:22,714     DEBUG        server.py                Соединение с клиентом ('127.0.0.1', 54590) закрывается.
2020-10-18 15:29:30,350     INFO         server.py                Запущен сервер, порт для подключений: 8079, адрес с которого принимаются подключения: 192.168.1.164. Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:29:33,842     INFO         server.py                Установлено соедение с ПК ('192.168.1.164', 54706)
2020-10-18 15:29:33,842     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603024173.842169, 'user': {'account_name': 'Guest'}}
2020-10-18 15:29:33,842     DEBUG        server.py                Разбор сообщения от клиента : {'action': 'presence', 'time': 1603024173.842169, 'user': {'account_name': 'Guest'}}
2020-10-18 15:29:33,842     INFO         server.py                Cформирован ответ клиенту {'response': 200}
2020-10-18 15:29:33,843     DEBUG        server.py                Соединение с клиентом ('192.168.1.164', 54706) закрывается.
2020-10-18 15:30:39,020     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 15:30:41,996     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 54711)
2020-10-18 15:30:41,996     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603024241.9952767, 'user': {'account_name': 'Guest'}}
2020-10-18 15:30:41,996     DEBUG        server.py                Разбор сообщения от клиента : {'action': 'presence', 'time': 1603024241.9952767, 'user': {'account_name': 'Guest'}}
2020-10-18 15:30:41,996     INFO         server.py                Cформирован ответ клиенту {'response': 200}
2020-10-18 15:30:41,996     DEBUG        server.py                Соединение с клиентом ('127.0.0.1', 54711) закрывается.
2020-10-18 23:24:24,955     INFO         server.py                Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2020-10-18 23:24:29,422     INFO         server.py                Установлено соедение с ПК ('127.0.0.1', 51070)
2020-10-18 23:24:29,422     DEBUG        server.py                Получено сообщение {'action': 'presence', 'time': 1603052669.4226959, 'user': {'account_name': 'Guest'}}
2020-10-18 23:24:29,423     DEBUG        server.py                Разбор сообщения от клиента : {'action': 'presence', 'time': 1603052669.4226959, 'user': {'account_name': 'Guest'}}
2020-10-18 23:24:29,423     INFO         server.py                Cформирован ответ клиенту {'response': 200}
2020-10-18 23:24:29,423     DEBUG        server.py                Соединение с клиентом ('127.0.0.1', 51070) закрывается.
